language: rust

cache:
  # https://levans.fr/rust_travis_cache.html
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.rustup/

matrix:
  allow_failures:
    - name: "Android Debug Stable"
    - rust: nightly
  include:
    - name: "Linux Release Stable"
      os: linux
      rust: stable
      script: ["cargo test --verbose --release"]
    - name: "Linux Debug Stable"
      os: linux
      rust: stable
    - name: "Linux Debug Beta"
      os: linux
      rust: beta
    - name: "Linux Debug Nightly"
      os: linux
      rust: nightly
    - name: "Windows Debug Stable"
      os: windows
      rust: stable
    - name: "OS X Debug Stable"
      os: osx
      rust: stable
    - name: "iOS Debug Stable"
      os: osx
      rust: stable
      script:
        - rustup target install aarch64-apple-ios
        - cargo build --all --verbose --target=aarch64-apple-ios
    - name: "Android Debug Stable"
      os: linux
      dist: trusty
      language: android # https://docs.travis-ci.com/user/languages/android/
      android:
        components:
          #- tools
          #- platform-tools
          - build-tools-26.0.2
          - android-26
          #- sys-img-x86-android-26 # for eventual unit testing via simulator
      script:
        - echo travis_fold:start:rustup-install
        - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y
        - export PATH=${TRAVIS_HOME}/.cargo/bin:$PATH
        - echo travis_fold:end:rustup-install
        - rustup target install armv7-linux-androideabi
        - cargo build --all --verbose --target=armv7-linux-androideabi
    - name: "WASM Debug Stable"
      os: linux
      rust: stable
      script:
        - rustup target install wasm32-unknown-unknown
        - cargo-web version || cargo install cargo-web
        - cargo web build --verbose --target=wasm32-unknown-unknown

script:
  - cargo test --verbose --all

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
