language: rust
cache: cargo
matrix:
  allow_failures:
    - os: linux
    - os: osx
    - rust: nightly
  include:
    - name: "Linux Release Stable"
      os: linux
      rust: stable
      script: ["cargo test --verbose --release"]
    - name: "Linux Debug Stable"
      os: linux
      rust: stable
    - name: "Linux Debug Beta"
      os: linux
      rust: beta
    - name: "Linux Debug Nightly"
      os: linux
      rust: nightly
    - name: "Windows Debug Stable"
      os: windows
      rust: stable
    - name: "OS X Debug Stable"
      os: osx
      rust: stable
    - name: "Android Debug Stable"
      os: osx
      rust: stable
      script:
        - rustup target install armv7-linux-androideabi
        - cargo build --examples --verbose --target=armv7-linux-androideabi
    - name: "WASM Debug Stable"
      os: osx
      rust: stable
      script:
        - rustup target install wasm32-unknown-unknown
        - cargo install cargo-web
        - cargo web build --verbose --target=wasm32-unknown-unknown

script:
  - cargo test --verbose --all
