language: rust

branches:
  except:
    - /^v\d+\.\d+\.\d+$/  # Exclude tags in the style of v1.2.3
    - /^dead\/.+$/        # Exclude dead/* branches from CI, they're dead for a reason

cache:
  # https://levans.fr/rust_travis_cache.html
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.rustup/

matrix:
  allow_failures:
    - rust: nightly
  include:
    - { name: "Linux Release Stable", os: linux,    rust: stable, script: ["cargo test --verbose --release"] }
    - { name: "Linux Debug 1.36.0",   os: linux,    rust: 1.36.0  }
    - { name: "Linux Debug Stable",   os: linux,    rust: stable  }
    - { name: "Linux Debug Beta",     os: linux,    rust: beta    }
    - { name: "Linux Debug Nightly",  os: linux,    rust: nightly }
    - { name: "Windows Debug Stable", os: windows,  rust: stable  }
    - { name: "OS X Debug Stable",    os: osx,      rust: stable  }
    - { name: "iOS Debug Stable",     os: osx,      rust: stable, script: ["cargo build --all --verbose --target=aarch64-apple-ios"], install: ["rustup target install aarch64-apple-ios"] },

    - name: "Android Debug Stable"
      os: linux
      dist: trusty
      language: android # https://docs.travis-ci.com/user/languages/android/
      android:
        components:
          #- tools
          #- platform-tools
          - build-tools-26.0.2
          - android-26
      install:
        - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y
        - export PATH=${TRAVIS_HOME}/.cargo/bin:$PATH
        - echo y | sdkmanager "ndk-bundle"
        - export PATH=/usr/local/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        - rustup target install armv7-linux-androideabi
      script:
        - pushd scripts/linux-android
        - cargo build --all --verbose --target=armv7-linux-androideabi
        - popd

    - name: "WASM Debug Stable"
      os: linux
      rust: stable
      install:
        - rustup target install wasm32-unknown-unknown
        - cargo-web --version || cargo install cargo-web
      script:
        - cargo web build --verbose --target=wasm32-unknown-unknown

script:
  - cargo test --verbose --all

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
